# Generated by Django 6.0.2 on 2026-03-27 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_requestmanager_helper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmanager',
            name='interested_helpers',
        ),
        migrations.RemoveField(
            model_name='requestmanager',
            name='matched_helper',
        ),
        migrations.AddField(
            model_name='requestmanager',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestmanager',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Matched', 'Matched')], default='Open', max_length=50),
        ),
    ]
