# Generated by Django 6.0.2 on 2026-03-27 04:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_requestmanager_interested_helpers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanager',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applied_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
