# Generated by Django 6.0.2 on 2026-03-27 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_requestmanager_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmanager',
            name='helper',
        ),
        migrations.AddField(
            model_name='requestmanager',
            name='matched_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestmanager',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Matched', 'Matched')], default='Pending', max_length=50),
        ),
    ]
