# Generated by Django 6.0.2 on 2026-03-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_listing_image_url_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanager',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
