# Generated by Django 6.0.2 on 2026-03-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_requestmanager_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmanager',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
